### PR TITLE
LEAN-2415: SSec-037 - Update manuscripts data

### PR DESCRIPTION
**Pull request by mbetamony**
Updated the section-categories.json to include the new section categories: 

1. MPSectionCategory:abstracts
2. MPSectionCategory:backmatter
3. MPSectionCategory:body

And based on Nick's comment in [Section handling](https://confluence.atypon.com/display/E2E/Special+Section+handling ), I removed the sections that don't have an **_Article section_** 

> Our initial implementation will apply the same category drop down for both Ceres OPS and the Dashboard. So "common for the Editor" wherever it is used. And what we want is whatever is specified here to be for Ceres OPS

I resorted the list alphabetically based on priorities. 

I also suggest we use the priority field in each Section Category to show/hide the section in the drop down list instead of using the groupIDs field. we can make it such that if a priority field exists then we can show it, if not then we can hide it. (the current implementation will hide/show based on the groupIDs field)

### CODE REVIEW

**Review by asouqi — CHANGES_REQUESTED** [review]
> I resorted the list alphabetically based on priorities.

please revert that, as we do it in the component that uses the list.

> I also suggest we use the priority field in each Section Category to show/hide the section in the drop down list instead of using the groupIDs field. we can make it such that if a priority field exists then we can show it, if not then we can hide it.

we can't do that as we use priority to validate section order, look at the [manuscripts-requirements](https://github.com/Atypon-OpenSource/manuscripts-requirements)

**Comment by mnatsheh** [comment]
Using priority to both sort the list in the UI, and for validation seems weird to me. Let's not worry about manuscripts-requirements for now.

@mbetamony are you sure all the categories you removed are not used anywhere? 

----
> I also suggest we use the priority field in each Section Category to show/hide the section in the drop down list instead of using the groupIDs field. we can make it such that if a priority field exists then we can show it, if not then we can hide it. (the current implementation will hide/show based on the groupIDs field)

I'm not sure how this would work. Whether a category is shown in the dropdown will also depend on the "active" group, so the groupID needs to be checked.

**Comment by mbetamony** [comment]
I added a commit that restores the deleted sections. I found some usages for some of these sections.

> Using priority to both sort the list in the UI, and for validation seems weird to me. Let's not worry about manuscripts-requirements for now.
> 
> @mbetamony are you sure all the categories you removed are not used anywhere?
> 
> > I also suggest we use the priority field in each Section Category to show/hide the section in the drop down list instead of using the groupIDs field. we can make it such that if a priority field exists then we can show it, if not then we can hide it. (the current implementation will hide/show based on the groupIDs field)
> 
> I'm not sure how this would work. Whether a category is shown in the dropdown will also depend on the "active" group, so the groupID needs to be checked.

I meant reorder them by reevaluating the priority field, so when the FE editor sorts them the sections are sorted correctly 



> > I resorted the list alphabetically based on priorities.
> 
> please revert that, as we do it in the component that uses the list.
> 
> > I also suggest we use the priority field in each Section Category to show/hide the section in the drop down list instead of using the groupIDs field. we can make it such that if a priority field exists then we can show it, if not then we can hide it.
> 
> we can't do that as we use priority to validate section order, look at the [manuscripts-requirements](https://github.com/Atypon-OpenSource/manuscripts-requirements)

**Comment by asouqi** [comment]
> I meant reorder them by reevaluating the priority field, so when the FE editor sorts them the sections are sorted correctly

and this reevaluation based on the removed sections?

**Review by asouqi — CHANGES_REQUESTED** [review]
can you please merge the master into this branch?

**Comment by mbetamony** [comment]
@asouqi 

> can you please merge the master into this branch?

Done



> > I meant reorder them by reevaluating the priority field, so when the FE editor sorts them the sections are sorted correctly
> 
> and this reevaluation based on the removed sections?


After restoring the deleted sections, I rearranged the priorities accordingly

**Review by asouqi — APPROVED** [review]

**Comment by mbetamony** [comment]
@mnatsheh can you deploy this please

**Pull request merged**
